name: wick-desktop
base: core22
version: '0.1.0'
summary: WAMP API tester with a UI
description: |
  WAMP API tester with a UI

grade: stable
confinement: strict
compression: lzo

plugs:
  dot-wick:
    interface: personal-files
    write:
      - $HOME/.wick

apps:
  wick-desktop:
    command: wick-desktop
    extensions:
      - gnome
    plugs:
      - network
      - network-bind
      - home
      - dot-wick

parts:
  wick-desktop:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
