name: wick-desktop
base: core24
version: '0.2.0'
summary: API tester for WAMP protocol
description: |
  API tester for WAMP Protocol

grade: stable
confinement: strict
compression: lzo

plugs:
  dot-wick:
    interface: personal-files
    write:
      - $HOME/.wick

apps:
  wick-desktop:
    command: wick-desktop
    extensions:
      - gnome
    plugs:
      - network
      - network-bind
      - home
      - dot-wick

parts:
  wick-desktop:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
