name: XConnUI

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Install dependencies
        run: make install

      - name: Verify formatting
        run: make check-format

      - name: Check lint
        run: make lint

      - name: Build APK
        run: make build-apk

      - name: Run tests
        run: make tests
