name: Deploy web on S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Install dependencies
        run: make install

      - name: Build web app
        run: make build-web

      - name: Push Artifacts to Target Repo
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          # Set up target repository
          git config --global user.name "asimfarooq5"
          git config --global user.email "asimfarooq5@gmail.com"
          git clone https://x-access-token:${TARGET_REPO_TOKEN}@github.com/xconnio/wick-ui-artifacts.git
          # Copy artifacts to target repo
          cp -R build/web/* wick-ui-artifacts/
          cd wick-ui-artifacts
          # Commit and push changes
          git add .
          git commit -m "Update web artifacts from $GITHUB_SHA"
          git push
